### ISSUE TITLE
Cannot run _main.sh on Ubuntu/Debian

### ISSUE THREAD

**Issue by Perspekt** [aws-samples/amazon-eks-scaling-with-keda-and-karpenter#1]
$ sh ./deployment/_main.sh
./deployment/_main.sh: 5: source: not found
Please check the details before proceeding
 AWS Account:
 AWS Region for deployment :

Please check the Karpenter version you have selected is available at

  https://karpenter.sh

Also please check #Experiencing Issues# section before proceeding.

Casesenstive Press Y = Proceed or N = Cancel
Response:
Y
./deployment/_main.sh: 13: [[: not found
Cancel deployment

**Comment by khanasif1** [comment]
Please check the terminal path should be as per documentation. Please re-open if you still experience the issue
